version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
